- name: setup base
  hosts: servers
  become: true

  tasks:
      - name: update packages
        apt:
            update_cache: yes

      - name: upgrade packages
        apt:
            upgrade: dist

      - name: remove unnecessary packages
        apt:
            autoremove: yes

      - name: clean apt cache
        apt:
            autoclean: yes
