- name: setup ufw
  hosts: servers
  become: true

  tasks:
      - name: install ufw
        apt:
            name: ufw
            state: present
            update_cache: yes

      - name: allow nginx
        ufw:
            rule: allow
            name: Nginx HTTP

      - name: enable ufw
        ufw:
            state: enabled
            policy: deny
